// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jpassion.myproject.mydomain;

import com.jpassion.myproject.mydomain.Flight;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Flight_Roo_Configurable {
    
    declare @type: Flight: @Configurable;
    
}
